baseURL = "https://saasify-demo.chaoming.li/"
languageCode = "en-us"
title = "Wisdom Bits"

# Theme Config
theme = "hugo-saasify-theme"

# Enable syntax highlighting
pygmentsCodeFences = true
pygmentsUseClasses = true

# Enable emoji support
enableEmoji = true

# Enable Git info for lastmod
enableGitInfo = true

# Enable taxonomies
[taxonomies]
category = 'categories'
tag = 'tags'

# Pagination
paginate = 6
paginatePath = "page"

[params]
description = ""
author = "Liam Louw"
logo = "/images/Starting-card.svg"
# Google Analytics ID (e.g., "G-XXXXXXXXXX")
# googleAnalytics = "G-XXXXXXXXXX"

# Global CTA Configuration
[params.cta]
enable = true
title = "Ready for all bits of wisdom?"
description = "Join Christians around the world in sharing scripture in a simple, beautiful way."
gradient_from = "#2563eb"                                                                              # Indigo-600
gradient_to = "#7c3aed"                                                                                # Purple-600
gradient_angle = 30
[params.cta.primary_button]
text = "Get Started"
url = "/get-started"

# Social Media Links
[params.social]
linkedin = "https://linkedin.com/in/chaomingli"
# twitter = "https://twitter.com/lichaoming"
# youtube = "https://youtube.com/@chaomingli"
# facebook = "https://facebook.com/lichaoming"
instagram = "https://instagram.com/lichaoming"
github = "https://github.com/chaoming"

# Footer Configuration
[params.footer]
column_1_title = "COMPANY"
column_2_title = "LEGAL"

[params.header]
# Header background and border styles (optional)
background = "bg-white/80 backdrop-blur-sm"
border = "border-b border-gray-100"

# Logo configuration
[params.header.logo]
src = "/images/Starting-card.svg"

# Menu configuration
[params.header.menu]
spacing = "space-x-8"

# Dropdown menu configuration
[params.header.menu.dropdown]
width = "w-72"
container_padding = "py-6"
item_padding = "px-8 py-3"
background = "bg-white"
border = "border border-gray-100"
shadow = "shadow-xl"
radius = "rounded-lg"
text_color = "text-gray-700"
hover_background = "hover:bg-gray-50"
text_size = "text-sm"

# Button configuration
[params.header.buttons]

# Get Started button
[params.header.buttons.getStarted]
text = "Get Started"
url = "/get-started"

# Blog configuration
[params.blog]
enable = true

# Blog CTA configuration
[params.blog.cta]
enable = true # Enable/disable CTA in blog posts

# Sidebar configuration
[params.blog.sidebar]
# Recent articles section
[params.blog.sidebar.recent]
enable = true
title = "Recent Articles"
count = 5

# Categories section
[params.blog.sidebar.categories]
enable = true
title = "Categories"

# Tags section
[params.blog.sidebar.tags]
enable = true
title = "Popular Tags"
count = 20

# Subscribe form section
[params.blog.sidebar.subscribe]
enable = true
title = "Subscribe to Newsletter"
description = "Get the latest posts delivered right to your inbox"
action = "https://formspree.io/f/your-form-id"
emailName = "email"
buttonText = "Subscribe"
placeholder = "Enter your email"
disclaimer = "We respect your privacy. Unsubscribe at any time."

[module]
[module.hugoVersion]
extended = true
min = "0.80.0"

[build]
writeStats = true

[build.buildStats]
enable = true

[security.funcs]
getenv = ['^HUGO_', '^CI$']

[markup]
[markup.highlight]
noClasses = false
lineNos = true
codeFences = true
guessSyntax = true
lineNumbersInTable = true
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

# Navigation Menu
[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Pricing"
url = "/pricing"
weight = 2
[[menu.main]]
name = "Packs"
url = "/packs"
weight = 3
[[menu.main]]
name = "About Us"
url = "/about-us"
weight = 4

# Footer Column 1 Menu
[[menu.footer_column_1]]
name = "Packs"
url = "/packs"
weight = 1
[[menu.footer_column_1]]
name = "About Us"
url = "/company"
weight = 2
[[menu.footer_column_1]]
name = "Careers"
url = "/careers"
weight = 3

# Footer Column 2 Menu
[[menu.footer_column_2]]
name = "License"
url = "/license"
weight = 1
[[menu.footer_column_2]]
name = "Privacy Policy"
url = "/privacy"
weight = 2
